name: Build and Push PolySpace Docker Image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile.policy" # Only triggers if Dockerfile.policy changes
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.policy -t ghcr.io/${{ github.repository_owner }}/polyspace-image:latest \
            --build-arg MATLAB_RELEASE=r2024b \
            --build-arg LICENSE_SERVER=${{ secrets.LICENSE_SERVER }} .

      # Step 4: Push Docker Image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/polyspace-image:latest
