name: dagger
on:
  pull_request:
    branches:
      - golang

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Call Dagger Function to build and publish to ghcr.io
      #   uses: dagger/dagger-for-github@v6
      #   with:
      #     version: "latest"
      #     verb: call
      #     args: build-and-push --registry=$DOCKER_REGISTRY --image-name=$DOCKER_IMAGE_NAME --source=.
      #     cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      #   env:
      #     DOCKER_REGISTRY: ghcr.io
      #     DOCKER_IMAGE_NAME: ${{ github.repository }}

      # - name: Setup Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: "1.21"

      # - name: Install Dagger CLI
      #   run: |
      #     cd /usr/local
      #     wget -O dagger.tar.gz https://github.com/dagger/dagger/releases/latest/download/dagger_v0.9.3_linux_amd64.tar.gz
      #     tar xzf dagger.tar.gz
      #     chmod +x dagger
      #     mv dagger /usr/local/bin/dagger

      # - name: Run Dagger Pipeline
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     REGISTRY: ghcr.io
      #     IMAGE_NAME: ${{ github.repository }}
      #   run: go run ./main.go

      - name: Scan the Code
        uses: dagger/dagger-for-github@v6
        with:
          version: "0.9.10"
          # version: "latest"
          verb: call
          module: ./fastapi-dagger
          args: scanAndPR --pull_request_number=$PR_NUMBER --github_repo=$GITHUB_REPOSITORY --github_token=$GITHUB_TOKEN --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      # - name: Call Dagger Function
      #   uses: dagger/dagger-for-github@v6
      #   with:
      #     version: "latest"
      #     verb: call
      #     module: ./hello
      #     args: hello --greeting="bonjour" --name="monde"
      #     cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
