name: dagger
on:
  pull_request:
    branches:
      - golang

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Call Dagger Function to build and publish to ghcr.io
      #   uses: dagger/dagger-for-github@v6
      #   with:
      #     version: "latest"
      #     verb: call
      #     args: build-and-push --registry=$DOCKER_REGISTRY --image-name=$DOCKER_IMAGE_NAME --source=.
      #     cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      #   env:
      #     DOCKER_REGISTRY: ghcr.io
      #     DOCKER_IMAGE_NAME: ${{ github.repository }}

      - name: Scan the Code
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: scan-and-pr --pull_request_number=$PR_NUMBER --github_repo=$GITHUB_REPOSITORY --github_token=$GITHUB_TOKEN --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
